baseURL = "https://zhangjunfelix.github.io/thinkwrite2/"
languageCode = "en-us"
title = "Critical Thinking & English Writing II"
copyright = "Zhang Jun"

[params]
  mode = "auto"
  subtitle = "Argumentation • Critical Thinking • Exposition"
  mathjax = false
  katex = false
  useCDN = false
  customCSS = ["css/custom.css"]

# Top navigation

# Top navigation

[[menu.main]]
  name = "Home"
  pageRef = "/"
  weight = 1

[[menu.main]]
  name = "Syllabus"
  pageRef = "/syllabus"
  weight = 2

[[menu.main]]
  name = "Intro"
  pageRef = "/intro"
  weight = 3

[[menu.main]]
  name = "Critical Thinking"
  pageRef = "/criticalthinking"
  weight = 4

[[menu.main]]
  name = "Paragraph Writing"
  pageRef = "/paragraphwriting"
  weight = 5

[[menu.main]]
  name = "Exposition"
  pageRef = "/exposition"
  weight = 6

[[menu.main]]
  name = "Argumentation Intro"
  pageRef = "/argumentationintro"
  weight = 7

[[menu.main]]
  name = "Argumentation Skills"
  pageRef = "/argumentationskills"
  weight = 8

[[menu.main]]
  name = "Types of Arguments"
  pageRef = "/typesofarguments"
  weight = 9

[[menu.main]]
  name = "Counter-Arguments"
  pageRef = "/counterarguments"
  weight = 10

[[menu.main]]
  name = "Persuasion"
  pageRef = "/persuasion"
  weight = 11

[[menu.main]]
  name = "Fallacies"
  pageRef = "/fallacies"
  weight = 12

[[menu.main]]
  name = "Final Practice"
  pageRef = "/finalpractice"
  weight = 13

[module]
  [[module.imports]]
    path = "github.com/athul/archie"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

ignoreLogs = ['warning-goldmark-raw-html']